apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms20cs093-nginx-deployment
  namespace: ms20cs093
  labels:
    app: ms20cs093-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms20cs093-nginx
  template:
    metadata:
      labels:
        app: ms20cs093-nginx
    spec:
      containers:
      - name: nginx
        image: 172.1.14.168:5001/nginx
        ports:
        - containerPort: 80
