apiVersion: v1
kind: Pod
metadata:
  name: ubuntunew
              namespace: ms20cs93
  labels:
    app: ubuntunew
spec:
  containers:
  - name: ubuntunew
    image: 172.1.14.168:5001/ubuntu
    env:
      - name: MESSAGE
        value: "Hello MSRIT"
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
