apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
              namespace: ms20cs93
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: 172.1.14.168:5001/ubuntu
    command: ["/bin/bash"]
    args: ["-c", "echo MSRIT"]
