kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: 172.1.14.168:5001/ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 5; done"]
    - name: c01
      image: 172.1.14.168:5001/httpd
      ports:
        - containerPort: 80
